config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  	registrations: 'users/registrations',
  	sessions: "users/sessions",
  	passwords: "users/passwords",
  }

  devise_scope :user do
    authenticated :user do
      root 'job_posts#new', as: :root
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end

  resources :job_posts, path: 'jobs' do
    put :claim
  	match '/listing' =>  'job_posts#listing', as: :jobs_listing, via: [:get], on: :collection
  end
end

app/views/shared/_breadcrumbs.html.erb
<% breadcrumbs.tap do |links| %>
  <% if links.any? %>
	<ul class="breadcrumb">
	    <% links.each do |link| %>
	      <li class="breadcrumb-item">
	      <% if link.current?  %>
	      	<span><%= link.text %></span>
	      <% else %>
	      	<%= link_to link.text, link.url %>
	      <% end %>
	      </li>
	    <% end %>
	</ul>
  <% end %>
<% end %>

app/views/shared/_left_sidebar.html.erb
<!--  START - Main Menu -->
<div class="menu-w color-scheme-light color-style-default menu-position-side menu-side-left menu-layout-compact sub-menu-style-over sub-menu-color-bright selected-menu-color-light menu-activated-on-hover">
  <a class="logo" href="<%#= pbt_dashboards_path %>">
    <%= image_tag "sst_logo.png", class: "logged-user-w avatar-inline", width: "250px", height: "200px;" %>
  </a>

  <div class="logged-user-w avatar-inline">
    <div class="logged-user-i">
      <div class="avatar-w">
        <%= image_tag "no_avatar.png" %>
      </div>
      <div class="logged-user-info-w">
        <div class="logged-user-name">
          <%= current_user.name %>
        </div>
      </div>
    </div>
  </div>

  <ul class="main-menu">
    <li>
      <a href="<%= new_job_post_path %>">
        <div class="icon-w">
          <div class="os-icon os-icon-layout"></div>
        </div>
        <span>Create Job</span>
      </a>
    </li>
    <li>
      <a href="<%= job_posts_path %>">
        <div class="icon-w">
          <div class="os-icon os-icon-layout"></div>
        </div>
        <span>My Jobs</span>
      </a>
    </li>
    <li>
      <a href="<%= jobs_listing_job_posts_path %>">
        <div class="icon-w">
          <div class="os-icon os-icon-file-text"></div>
        </div>
        <span>Job Listing</span>
      </a>
    </li>
    <li>
      <%= link_to(destroy_user_session_path, method: :delete) do %>
      <div class="icon-w">
        <div class="os-icon os-icon-signs-11"></div>
      </div>
      <span>Logout</span>
      <% end if user_signed_in? %>
    </li>
  </ul>

</div>
<!--  END - Main Menu -->

app/views/shared/_mobile_menu.html.erb
<!--------------------
START - Mobile Menu
-------------------->
<div class="menu-mobile menu-activated-on-click color-scheme-dark">
  <div class="mm-logo-buttons-w">
    <a class="mm-logo" href="<%#= dashboards_path %>">
      <%= image_tag "sst_logo.png" %>
      <span>GoGet</span>
    </a>
    <div class="mm-buttons">
      <div class="mobile-menu-trigger">
        <div class="os-icon os-icon-hamburger-menu-1"></div>
      </div>
    </div>
  </div>
  <div class="menu-and-user">
    <div class="logged-user-w">
      <div class="avatar-w">
          <%= image_tag "no_avatar.png" %>
]      </div>
      <div class="logged-user-info-w">
        <div class="logged-user-name">
          <%= current_user.name %>
        </div>
        <div class="logged-user-role">
          Administrator
        </div>
      </div>
    </div>
    <!--------------------
    START - Mobile Menu List
    -------------------->
    <ul class="main-menu">
      <li>
        <a href="">
          <div class="icon-w">
            <div class="os-icon os-icon-window-content"></div>
          </div>
          <span>Dashboard</span></a>
      </li>
      <li class="has-sub-menu">
        <a href="#">
          <div class="icon-w">
            <div class="os-icon os-icon-edit-32"></div>
          </div>
          <span>Content</span></a>
        <ul class="sub-menu">
          <li>
            <a href="">All Content</a>
          </li>
          <li>
            <a href="">Add New</a>
          </li>
        </ul>
      </li>
    </ul>
    <!--------------------
    END - Mobile Menu List
    -------------------->
  </div>
</div>
<!--------------------
END - Mobile Menu
-------------------->