config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  	registrations: 'users/registrations',
  	sessions: "users/sessions",
  	passwords: "users/passwords",
  }

  devise_scope :user do
    authenticated :user do
      root 'job_posts#new', as: :root
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end

  resources :job_posts, path: 'jobs' do
    put :claim
  	match '/listing' =>  'job_posts#listing', as: :jobs_listing, via: [:get], on: :collection
  end
end

app/models/job_post.rb
class JobPost < ActiveRecord::Base
  belongs_to :hirer, class_name: "User", foreign_key: 'hirer_id', optional: true
  belongs_to :hiree, class_name: "User", foreign_key: 'hiree_id', optional: true

  scope :as_hirer, ->(id) {where(hirer: id)}
  scope :as_hiree, ->(id) {where(hiree: id)}
  scope :available, -> {where(hiree: nil)}

  enum status: [:unclaimed, :claimed]

  geocoded_by :pickup_address, latitude: :pickup_latitude, longitude: :pickup_longitude

  def self.distance
    self.distance_to([self.pickup_latitude,self.pickup_longitude], :km).round(2) * 1000
  end
end

app/controllers/job_posts_controller.rb
class JobPostsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :set_job_claim, only: [:claim]
  before_action :current_location, only: [:listing]

  def index
    authorize JobPost
    @hirer_jobs = JobPost.as_hirer(current_user)
    @hiree_jobs = JobPost.as_hiree(current_user)

    respond_to do |format|
      format.html
      format.json { head :no_content }
    end
  end

  def listing
    authorize JobPost
    @jobs = JobPost.available.near(current_location, 1000, :units => :km, :order => 'distance')

    respond_to do |format|
      format.html
      format.json { head :no_content }
    end
  end

  def claim
    authorize @job
    @job.update_attributes(status: :claimed, hiree: current_user)
    respond_to do |format|
      format.html { redirect_to job_posts_path, notice: 'Job successfully claimed.' }
      format.json { head :no_content }
    end
  end

  def new
    authorize JobPost
    @job = JobPost.new
    respond_to do |format|
      format.html
      format.json { head :no_content }
    end
  end

  def edit
    authorize @job
    respond_to do |format|
        format.html
        format.json { head :no_content }
    end
  end

  def create
    authorize JobPost
    @job = JobPost.new(job_post_params.merge hirer: current_user)

    respond_to do |format|
      if @job.save!
        format.html { redirect_to job_posts_path, notice: 'Job was successfully created.' }
        format.json { render action: 'show', status: :created, location: @job }
      else
        format.html { render action: 'new' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @job
    respond_to do |format|
      if @job.update(job_post_params)
        format.html { redirect_to job_posts_path, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @job
    @job.destroy
    respond_to do |format|
      format.html { redirect_to job_posts_path }
      format.json { head :no_content }
    end
  end

  private
    def set_job
      @job = JobPost.find(params[:id])
    end

    def set_job_claim
      @job = JobPost.find(params[:job_post_id])
    end

    def current_location
        user_ip_address = if Rails.env.staging?
          current_user.current_sign_in_ip
        else
          Net::HTTP.get(URI.parse('http://checkip.amazonaws.com/')).squish
        end
        location = Geocoder.search(user_ip_address).first
        [location.latitude, location.longitude]
    end

    def job_post_params
      params.require(:job_post).permit(:title, :pickup_address, :pickup_latitude, :pickup_longitude, :dropoff_address,
                                       :dropoff_latitude, :dropoff_longitude, :hirer_id, :hiree_id)
    end
end

app/views/job_posts/_form.html.erb
<%= form_with(model: @job, id: "new_job_post", local: true) do |f| %>
<h5 class="form-header">
  Create Job
</h5>
<div class="google_map_section" id="gmap-section">
  <fieldset class="form-group">
    <legend></legend>
    <!-- display google map -->
    <!-- display selected location information -->
    <p><b>Pickup Location Details</b></p>
    <div id="geomap" style="width: 100%;height: 300px;"></div><br/>
    <div class="form-group">
      <label for="">Pickup Address</label>
      <%= f.text_field :pickup_address, class: "pickup_addr form-control", id: "search_location" ,required: "required"  %>
      <div class="help-block form-text with-errors form-control-feedback"></div>
    </div>
    <div class="row">
      <div class="col-sm-4">
        <div class="form-group">
          <label for="">Pickup Latitude</label>
          <%= f.text_field :pickup_latitude, class: "pickup_latitude form-control", placeholder: "Pickup Latitude", required: "required" %>
          <div class="help-block form-text with-errors form-control-feedback"></div>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group">
          <label for="">Pickup Longitude</label>
          <%= f.text_field :pickup_longitude, class: "pickup_longitude form-control", placeholder: "Pickup Longitude", required: "required" %>
          <div class="help-block form-text with-errors form-control-feedback"></div>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group">
          <label for="">&nbsp;&nbsp;</label>
          <input id="submit-latlng" type="button" value="Search By Lat/Long" class="btn btn-primary form-control" style="height: 35px;">
        </div>
      </div>
    </div>
  </fieldset>
  <hr>
  <fieldset class="form-group">
    <legend></legend>
    <!-- display google map -->
    <!-- display selected location information -->
    <p><b>Drop-off Location Details</b></p>
    <div id="dropoff-geomap" style="width: 100%;height: 300px;"></div><br/>
    <div class="form-group">
      <label for="">Drop-off Address</label>
      <%= f.text_field :dropoff_address, class: "dropoff_addr form-control", id: "search_dropoff_location", required: "required" %>
      <div class="help-block form-text with-errors form-control-feedback"></div>
    </div>
    <div class="row">
      <div class="col-sm-4">
        <div class="form-group">
          <label for="">Drop-off Latitude</label>
          <%= f.text_field :dropoff_latitude, class: "dropoff_latitude form-control", placeholder: "Drop-off Latitude", required: "required" %>
          <div class="help-block form-text with-errors form-control-feedback"></div>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group">
          <label for="">Drop-off Longitude</label>
          <%= f.text_field :dropoff_longitude, class: "dropoff_longitude form-control", placeholder: "Drop-off Longitude", required: "required" %>
          <div class="help-block form-text with-errors form-control-feedback"></div>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="form-group">
          <label for="">&nbsp;&nbsp;</label>
          <input id="submit-dropoff-latlng" type="button" value="Search By Lat/Long" class="btn btn-primary form-control" style="height: 35px;">
        </div>
      </div>
    </div>
  </fieldset>
	  <div class="form-buttons-w text-right">
	    <%= link_to "Cancel", job_posts_path, class: "btn btn-outline-primary" %>
	    <%= button_tag "Create", class: "btn btn-primary" %>
	  </div>
</div>
<% end %>

app/views/job_posts/index.html.erb
<% breadcrumb :job_posts, @job_posts %>
<div class="content-i">
  <div class="content-box">
    <div class="row">
      <div class="col-sm-12">
        <div class="element-wrapper">
          <div class="element-box">
            <div class="table-responsive">
              <h5 class="form-header">
                My Posted Job
              </h5>
              <table class="table table-lightborder">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Pickup Location</th>
                    <th>Drop-off Location</th>
                    <th>Created At</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  <% @hirer_jobs.each do |job|%>
                    <tr>
                      <td><%= job.id %></td>
                      <td><%= job.pickup_address %></td>
                      <td><%= job.dropoff_address %></td>
                      <td><%= job.created_at.to_s(:date_with_time) %></td>
                      <td><%= job.status %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              <br/><hr><br/>
              <h5 class="form-header">
                My Claimed Job
              </h5>
              <table class="table table-lightborder">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Pickup Location</th>
                    <th>Drop-off Location</th>
                    <th>Created At</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  <% @hiree_jobs.each do |job|%>
                    <tr>
                      <td><%= job.id %></td>
                      <td><%= job.pickup_address %></td>
                      <td><%= job.dropoff_address %></td>
                      <td><%= job.created_at.to_s(:date_with_time) %></td>
                      <td><%= job.status %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/job_posts/listing.html.erb
<% breadcrumb :job_listing %>
<div class="content-i">
  <div class="content-box">
    <div class="row">
      <div class="col-sm-12">
        <div class="element-wrapper">
          <div class="element-box">
            <div class="table-responsive">
              <h5 class="form-header">
                Jobs Nearby Me
              </h5>
              <table class="table table-lightborder">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Pickup Location</th>
                    <th>Drop-off Location</th>
                    <th>Distance ( from your current location to Pickup Location )</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  <% @jobs.each do |job|%>
                    <tr>
                      <td><%= job.id %></td>
                      <td><%= job.pickup_address %></td>
                      <td><%= job.dropoff_address %></td>
                      <td><%= job.distance.round(1).to_s + "km" %></td>
                      <td><%= policy(job).claim? ? (link_to "Claim", job_post_claim_path(job), method: :put, class: "btn btn-primary") : "Posted By You" %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/job_posts/new.html.erb
<% breadcrumb :new_job_post %>
<div class="content-i">
  <div class="content-box">
    <div class="row">
      <div class="col-sm-12">
        <div class="element-wrapper">
          <div class="element-box">
            <%= render "form" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>